import type { Metadata } from "next";
import { ADLaM_Display } from "next/font/google";
import "../globals.css";
import NavBar from "../components/NavBar";

const adlamDisplay = ADLaM_Display({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-adlam-display",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${adlamDisplay.variable} antialiased`}>
        <NavBar />
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
